### ISSUE TITLE
重复渲染两次

### ISSUE THREAD

**Issue by lamprose** [d0j1a1701/LiteLoaderQQNT-Markdown#10]
超链接（包含网络图片）后面带有文字，文字会重复两遍
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/29279979/bf0cd91e-7fe2-4682-90ba-176129e25d44)

**Comment by lamprose** [comment]
qq版本是: 9.9.0-14619 (64位) Win11 22H2

**Comment by lamprose** [comment]
系统版本是Win11 22H2
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/29279979/e484421e-e0e0-4ae3-8a7a-e69332bb9d5b)

**Comment by Ikaleio** [comment]
分段渲染的锅，正在进行重写渲染器

**Comment by Ikaleio** [comment]
有一件神奇的事情... 我还没修 结果修完那个无法加载的 bug 它自己就好了

请更新到 v3 分支最新版
