### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by xinyihl** [d0j1a1701/LiteLoaderQQNT-Markdown#11]
如果没有配置页面建议移除renderer.js中的onConfigView()
不然在设置里有一个空的设置页面
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/75861358/aa381385-42c8-4a9e-8f48-e8c21e152535)

**Comment by Ikaleio** [comment]
已修改，请更新。
