### ISSUE TITLE
安裝後導致所有插件及官方配置頁面消失

### ISSUE THREAD

**Issue by TW527E** [d0j1a1701/LiteLoaderQQNT-Markdown#15]
正常情況下為這樣的
![正常-圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/37478187/060f5969-3c61-492b-a8b5-f01fef90749b)
安裝後的情況
![安裝後-圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/37478187/39e71f5a-3ba8-44d4-b6ca-cbabeea6ce75)
即便將所有的 `file://` 替換為 `llqqnt://local-file/` 也是無法正常顯示的
拜託作者啦!

**Comment by Ikaleio** [comment]
发一下控制台截图~

**Comment by TW527E** [comment]
![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/37478187/a1c68ed2-ee12-48c9-8349-40e49da38766)
😅 怎麼看紀錄w

**Comment by Ikaleio** [comment]
已修复 请更新
