### ISSUE TITLE
使用赫蹏替代pangu.js

### ISSUE THREAD

**Issue by KagaJiankui** [d0j1a1701/LiteLoaderQQNT-Markdown#16]
[MSpring-Theme](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme)使用排版能力更好的[赫蹏](https://github.com/sivan/heti)替代了pangu.js。有没有可能将pangu.js升级到赫蹏？

**Comment by Ikaleio** [comment]
以后的版本会处理，我担心赫蹏与其他 CSS 的兼容问题。
