### ISSUE TITLE
白天模式下自己发出的链接颜色与气泡近乎一致

### ISSUE THREAD

**Issue by lxymahatma** [d0j1a1701/LiteLoaderQQNT-Markdown#18]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/66151783/49ffb72d-822d-4e26-a9ee-217ff41f9bad)
正常情况下白天模式里自己发出的消息是白色的包括链接，现在链接和气泡都是蓝色导致有点难辨认链接具体内容

**Comment by Truraly** [comment]
+1

**Comment by yhzcake** [comment]
这个是默认超链接样式吧,用transitio加载个全局的超链接css样式试试

**Comment by nfnfgo** [comment]
感谢您的反馈。

确实是有这个问题，具体来说，是因为Markdown渲染器取代了QQ本身的`text-link`机制，并且使用了`<a>`元素，所以导致了该问题。正在着手尝试修复。

**Comment by nfnfgo** [comment]
请尝试更新到最新版。

如果此问题仍然存在，您可以重新开启本Issue。

**Comment by Lucas04-nhr** [comment]
现在似乎夜间模式仍然会导致可读性变差
- 白天模式普通状态与鼠标覆盖状态：
<img width="463" alt="image" src="https://github.com/user-attachments/assets/ec766dca-78dc-48be-8fb2-f2e2c7975d16">

- 夜间模式普通状态:
<img width="488" alt="image" src="https://github.com/user-attachments/assets/e03b1f1c-4404-4abf-b1b3-c9a8652301e1">

- 夜间模式鼠标覆盖状态：
<img width="492" alt="image" src="https://github.com/user-attachments/assets/0f535848-7572-41a6-8945-04c809700981">

---
希望能在插件设置中增加自定义四种状态的字体颜色选项或者沿用QQ本身的text-link样式。
