### ISSUE TITLE
无法换行

### ISSUE THREAD

**Issue by LittleChest** [d0j1a1701/LiteLoaderQQNT-Markdown#19]
在安装插件后发送普通带换行的消息时不会正确渲染换行
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/81231195/d328a845-66cf-4114-99f5-974606e5a667)

**Comment by nep-0** [comment]
`main.js` 第 14 行 `false` 改成 `true` 就行了。

```
        breaks: false, // 转换段落里的 '\n' 到 <br>。
```
改成：
```
        breaks: true, // 转换段落里的 '\n' 到 <br>。
```

**Comment by Ikaleio** [comment]
应当已在 1.1.0 中修复
