### ISSUE TITLE
装完这个插件直接打开不了qq

### ISSUE THREAD

**Issue by bty552** [d0j1a1701/LiteLoaderQQNT-Markdown#2]
装完这个插件直接打开不了qq

**Comment by BAKAOLC** [comment]
main.js里面liteloader.plugins.markdown_it.path.plugin中的markdown_it取不到，应该是加载流程的问题
一个比较简单 ~（且野蛮）~ 的方法是自己修改代码把
```js
    const plugin_path = liteloader.plugins.markdown_it.path.plugin;
```
修改为
```js
    const plugin_path = "./..";
```
然后就能用了

**Comment by Ikaleio** [comment]
> 装完这个插件直接打开不了qq

@bty552 请更新到 0.1.1 插件版本，应该修复了这个问题
