### ISSUE TITLE
liteloaderqqnt更新1.0.0了  咱要不适配一下？

### ISSUE THREAD

**Issue by misaka10384** [d0j1a1701/LiteLoaderQQNT-Markdown#20]
[官网](https://liteloaderqqnt.github.io/docs/introduction.html)

**Comment by CJReinforce** [comment]
I submitted a PR #21 
我提交了pr

**Comment by misaka10384** [comment]
> I submitted a PR #21 我提交了pr

好  nice  太棒了  干得漂亮

**Comment by Ikaleio** [comment]
Done.
