### ISSUE TITLE
表情前会有神秘换行

### ISSUE THREAD

**Issue by Eletary** [d0j1a1701/LiteLoaderQQNT-Markdown#22]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/86780576/e7806688-66ff-453d-9222-9bfdc8980ecd)

关闭本插件后无换行

表情是系统自带表情

**Comment by mslxl** [comment]
我尝试定位了一下问题，这似乎是因为在 QQ 中的一条消息并不在同一个标签中，而是被放在多个标签中进行渲染。例如消息 `prefix😂suffix`（用emoji代替QQ内表情）是在三个 span 中。这三个 span 分别在 markdown-it 中渲染，会被视为单独的 markdown 语句并产生对应标签。例如`prefix😂suffix`的结果是 `<span><p>prefix</p></span> <span><img/></span> <span><p>suffix</p></span>`

同样，超链接等其他非文本内容也会产生相同的情况。这个问题似乎比想象中的更加严重，因为是把每个span都单独视为一个 markdown 块，像是 `prefix😂# this should not be title` 的后部分将被视为标题


#31 #25 均是同样原因

[相关代码](https://github.com/mslxl/LiteLoaderQQNT-Markdown/blob/0d1be2ad41fd37eee2a2df22fc61f0d1326e3863/src/renderer.js#L5-L7)
