### ISSUE TITLE
[bug] 部分语法无法正确识别

### ISSUE THREAD

**Issue by yhzcake** [d0j1a1701/LiteLoaderQQNT-Markdown#23]
![7f6ec6c68c531a1686c5f690ec44deda](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/80627671/f898a845-c0b4-4560-888a-474abf9265e5)
如图,部分标题未正确识别

那个目录折叠估计大概率不会被支持,所以就无所谓了(((

**Comment by yume233** [comment]
内嵌HTML也无法解析，这是正常的吗

**Comment by Ikaleio** [comment]
内迁 HTML 可能会造成严重的 XSS 注入问题，最简单的解决方案就是直接封死，正如大部分支持 Markdown 的论坛。

**Comment by Ikaleio** [comment]
奇妙的渲染问题应当已在 1.1.0 中修复
