### ISSUE TITLE
与Telegram主题不兼容

### ISSUE THREAD

**Issue by 8MiYile** [d0j1a1701/LiteLoaderQQNT-Markdown#26]
### 问题描述
LLNTQQ只加载Telegram主题和这个插件，在夜间模式下聊天文本会强制设置成黑色，然后气泡本身也是灰黑，导致视觉效果很差

### 预期
默认文本跟随主题设置的颜色 哪怕是前面带#号的

### 如何发现
在装了一堆插件和Telegram主题后，我发现发送的文本是黑色的，但是主题内设置却不是黑色的，所以我就逐个插件取消插件，到了禁用Markdown插件后，文本颜色随即正常

**Comment by nfnfgo** [comment]
#51 

您两一个是浅色模式不行，一个是深色模式不行lol

不知道是不是出于同一个原因，如果是的话，下次PR merge之后应该就能修复了（）

**Comment by nfnfgo** [comment]
您好，该问题已经在最新版本中修复，请更新到插件最新版本。

**Comment by 8MiYile** [comment]
好的，主题和该插件都已最新，工作正常
