### ISSUE TITLE
程式碼區塊（codeblock）無法正確的顯示內文

### ISSUE THREAD

**Issue by EvanHsieh0415** [d0j1a1701/LiteLoaderQQNT-Markdown#29]
![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/a863deff-faa8-4e4d-b120-0062d7d02595)
![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/4731b8ae-9fd0-4467-994f-6f9f4a131b0a)

訊息原文：
> 官方給的範例做法則是
> ```js
> Platform.mods.kubejs.name = "New Create"
> ```

**Comment by mslxl** [comment]
似乎和 https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/issues/22#issuecomment-2053654702 是同样的原因，都是 QQ 将消息分为了多个 span 导致 markdown 被分为多份分别渲染。#32 应该解决了这个问题，能否测试一下呢

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/11132880/e14f3020-a2ec-4161-8d0d-4f51e908b765)
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/11132880/49096f6a-b2dc-469d-be57-03998d2bc2ec)

**Comment by Ikaleio** [comment]
应当已在 1.1.0 中修复
