### ISSUE TITLE
代码高亮建议加入白天模式

### ISSUE THREAD

**Issue by xh321** [d0j1a1701/LiteLoaderQQNT-Markdown#3]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/37585529/6391b407-b0ae-438b-b1eb-996cca702fe8)
如图

**Comment by Ikaleio** [comment]
你可以发现 src/style 里面有一个 hljs-github-light

你只需要将 main.js 里面的 hljs-github-dark 换成 hljs-github-light 即可，我正在制作 UI

**Comment by xh321** [comment]
建议跟QQ一样，能手动调白天、黑夜和自适应

**Comment by Ikaleio** [comment]
已经增加了自适应功能，随着QQ主题的变化而改变
