### ISSUE TITLE
建议添加不自动使用pangu.js分割功能并支持HTML

### ISSUE THREAD

**Issue by SPJ2025** [d0j1a1701/LiteLoaderQQNT-Markdown#31]
1.如标题所示，艾特和表情后面会有换行，影响观感
2.如标题所示，可以展示HTML内容

**Comment by mslxl** [comment]
自动换行问题是其他原因产生，与 pangu.js 无关

不过我也同意移除 pangu 或者添加配置项，不是所有的情况都需要自动加空格。有时发送的文件格式敏感，不能多出无关的空格，而 pangu 自动追加空格会造成很大的困扰。此外自动加空格不应该由 markdown 来做，而应该是其他插件去实现

**Comment by Ikaleio** [comment]
已经移除 pangu.js

**Comment by NeonSPJ** [comment]
> 已经移除 pangu.js

OK
