### ISSUE TITLE
括号渲染不正确

### ISSUE THREAD

**Issue by 502milk** [d0j1a1701/LiteLoaderQQNT-Markdown#33]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/49502047/658e2744-7083-452f-a694-0f04b09b912c)
应该为下图所示大长括号
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/49502047/22084231-7758-4df6-95ce-2cf8a532f479)

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/49502047/486aaee9-b131-459e-84c0-7acac3fd2adb)
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/49502047/3006d47c-55a9-4149-8478-3c0c0dfdbfdd)

插件版本1.1.0

**Comment by mslxl** [comment]
似乎是我在 #32 中引入的问题 😭

**Comment by 502milk** [comment]
> 似乎是我在 #32 中引入的问题 😭 

噎住...

**Comment by mslxl** [comment]
我确认了一下，括号太小并不是在 1.1.0 引入的，而是之前就存在的（未找到成因）。
```
$$
\begin{cases}
\frac{\partial z}{\partial x}  &= 3x^2 - 3 &= 0 \\\\
 \frac{\partial z}{\partial y}  &= 2y + 2 &= 0
\end{cases}
$$
```
1.0.0 显示效果如下:

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/11132880/0971bbba-ddc5-47e1-9688-4387b14c66aa)

不过 `&` 变成 `&amp;` 确实新引入的。近几天马上修

**Comment by 502milk** [comment]
好的，感谢

**Comment by nfnfgo** [comment]
Currently the code has been updated to support rendering all LaTeX fonts in right size. 

If you clone this repository, it should work after you following the dev docs to apply local changes to the latex plugin. 

However, **this workaround requires manual modifications to the KaTeX package, which cannot be performed by GitHub Actions**. As a result, the current `release.zip` generated by GitHub Actions will not include these changes, and the fonts will continue to be rendered at the incorrect size.

I think the simplest way to fix this is to move the modified version of the katex plugin into this repo.

**Comment by nfnfgo** [comment]
您好，该问题已经在最新版本中修复，请更新插件。

如果问题仍然未解决，您可以重新开启本Issue。
