### ISSUE TITLE
~~~顯示異常

### ISSUE THREAD

**Issue by EvanHsieh0415** [d0j1a1701/LiteLoaderQQNT-Markdown#35]
![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/b7aecd31-c30b-42db-92ca-13828aeaadfa)
![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/f17a626d-c54d-403d-b310-23e6d520eb29)
原文：
```
~~~foobar
```

**Comment by mslxl** [comment]
这是 markdown 的[扩展语法 Fenced Code Blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)啦，其显示效果就是代码块

**Comment by EvanHsieh0415** [comment]
草，也太不常見的語法

**Comment by EvanHsieh0415** [comment]
那沒事了
