### ISSUE TITLE
圖片顯示位置錯誤

### ISSUE THREAD

**Issue by EvanHsieh0415** [d0j1a1701/LiteLoaderQQNT-Markdown#37]
輸入時：![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/49989af7-39de-4a10-8fd9-003a57146d75)

安裝插件並發送後：![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/102937db-4865-46b9-af5f-73ef09a76544)

未安裝插件並發送後：![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/82c160d5-1c43-4bd5-b41e-45a71ca97b45)

**Comment by nfnfgo** [comment]
这个问题已经在`nf_dev` Branch的最新commit中得到修复，可能会于近日比如`v4`.

**Comment by nfnfgo** [comment]
请尝试更新到最新版本。

**Comment by EvanHsieh0415** [comment]
經確認已修復
