### ISSUE TITLE
引用（quote）未正常運作

### ISSUE THREAD

**Issue by EvanHsieh0415** [d0j1a1701/LiteLoaderQQNT-Markdown#38]
輸入時：![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/acf68d66-1e5d-488b-8328-a45a831eaede)

發送後：![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/4b455878-0b13-4144-b61d-9d1ebd8444b0)

理想效果：
> 123
> 456

**Comment by nfnfgo** [comment]
After some preliminary checks it seems that this issue arises from unparsed HTML entities.

Specifically, the **character '>' is converted to '\&gt;' in HTML**, which **causes the markdown parser to fail to recognize blockquote formatting**.

One quick fix is to **detect and replace all occurrences of `&gt;` into `>` in the retrieved innerHTML:**

```js
// renderer.js line37
return {
  mark: Array.from(msgPiece.getElementsByTagName("span"))
      .map((e) => e.innerHTML)
      .reduce((acc, x) => acc + x.replaceAll('&gt;', '>'), ""), // Here add .replaceAll('&gt;', '>')
  replace: null
}
```
There might be a more elegant solution, but this should work for now.

# Example

```
## Quote Test

> Here is a blockquote.
>
> Multi-line is available.

## Nested Quote Test

> Outer
>
> Some content.
>> Inner
>> Inner content.
```

Output Screenshot:

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/10f9d705-49d1-46f1-a9b7-5a3e4cb50a7b)

**Comment by Ikaleio** [comment]
[请更新到 2.0.0 版本](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/releases/tag/2.0.0)
