### ISSUE TITLE
请求添加是否开启功能选项

### ISSUE THREAD

**Issue by nullnoneNaN** [d0j1a1701/LiteLoaderQQNT-Markdown#39]
有时日常消息会因为匹配到markdown语法呈现出很奇怪的效果

**Comment by nfnfgo** [comment]
目前可以通过 LiteLoader 全局开启或关闭该插件。

**Comment by nfnfgo** [comment]
关于这个问题，我认为更符合直觉的做法是在单条消息下增加一个小按钮，允许用户切换显示渲染后和的消息和原消息，等过几天写完了我开个PR（或者说大伙有没有其他的想法）
