### ISSUE TITLE
自定义字体后显示错误

### ISSUE THREAD

**Issue by CN-Grace** [d0j1a1701/LiteLoaderQQNT-Markdown#43]
列表在使用“轻量工具箱”中自定义字体功能后，出现显示错误
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/36886729/f4cf9e72-e9ce-4513-a126-cf1e50fce351)

**Comment by nfnfgo** [comment]
最新版本还有这个问题吗

**Comment by CN-Grace** [comment]
> 最新版本还有这个问题吗

修复了修复了，麻烦大佬了
