### ISSUE TITLE
功能请求，是否能添加对html代码的渲染支持？

### ISSUE THREAD

**Issue by Aliorpse** [d0j1a1701/LiteLoaderQQNT-Markdown#44]
emm，是这样的，我使用qq机器人对接bingchat，返回的文本为markdown格式的文本，但是其中有一些不包括在markdown内的html标签 比如说sup上标，所以希望能有这个功能
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/98144240/6bda80ae-bd28-4dad-bbf0-f62d691b7810)

**Comment by Ikaleio** [comment]
[请更新到 2.0.0 版本](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/releases/tag/2.0.0)
