### ISSUE TITLE
[BUG] 与主题[StarRailUI]冲突

### ISSUE THREAD

**Issue by QingFeng-awa** [d0j1a1701/LiteLoaderQQNT-Markdown#45]
与主题[StarRailUI](https://github.com/SyrieYume/starrail_ui/tree/main)发生了冲突。
详情请见[[BUG] 深色模式下看不清消息 #4](https://github.com/SyrieYume/starrail_ui/issues/4)

**Comment by Ikaleio** [comment]
[请更新到 2.0.0 版本](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/releases/tag/2.0.0)
