### ISSUE TITLE
[建议]: 希望添加对行内latex的渲染

### ISSUE THREAD

**Issue by TranscendMa** [d0j1a1701/LiteLoaderQQNT-Markdown#50]
希望能够添加对于形如：
“计算 $ \log_{10}(4) $ 有如下步骤”
这样嵌入文本行中的latex公式的渲染。

如果这个需求过于小众，还请指点有无手动添加此类规则的方法 (～￣▽￣)～

**Comment by nfnfgo** [comment]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/c544a696-0475-4b02-9e37-6c208da34903)

该插件支持行内latex渲染，请去除latex公式内多余的空格即可： `$\log_{10}(4)$`

**Comment by TranscendMa** [comment]
感谢，现在可以正常渲染了
