### ISSUE TITLE
bug: 白天模式与Telegram主题不兼容

### ISSUE THREAD

**Issue by TranscendMa** [d0j1a1701/LiteLoaderQQNT-Markdown#51]
启用markdown-it插件会覆盖Telegram主题的设置，白天模式下会使自己的消息文本颜色为白色，从而导致辨识度较低；切换到夜间模式一切正常。
在单独关掉本插件后，白天模式下文字正常显示为黑色。

**Comment by nfnfgo** [comment]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/a3db68a9-f43e-485b-8f47-0e066b521596)

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/72eb73c2-4687-42a0-84c3-6f5e8a01c4f4)

您好，我在Windows环境下尝试复现失败，能否提供其他更详细的细节，如本插件版本号，LiteLoader插件列表截图等？如果可能，请进一步提供诸如元素审查界面截图和Console页面截图等可以协助定位问题的资料。

**Comment by TranscendMa** [comment]
很抱歉没有附上相关的版本信息。
LL版本    1.1.2
QQNT    9.9.11-24815
本插件版本为  2.1.0

插件列表如下：
![屏幕截图 2024-07-03 203909](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/121599515/8fb166c4-4f98-498d-8cad-dd5a9db56182)
![屏幕截图 2024-07-03 203922](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/121599515/a1f07859-51ae-4530-9317-6bbd940d4e0b)
![屏幕截图 2024-07-03 203931](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/121599515/1eeb68d3-bc98-438e-85f2-99dabd3e097c)


在白天/黑夜模式的显示效果如下：
![屏幕截图 2024-07-03 203752](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/121599515/74b1233c-70a2-4af6-8fa3-7675b04eebc4)
![屏幕截图 2024-07-03 203806](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/121599515/8ad3f8ea-a2e7-459b-9bd6-fc28497ca5c5)


审查元素目前不是很会弄，如果需要其相关的信息，请描述一下如何进入元素审查界面，我会再进行尝试。




碎碎念：在调试的时候，遇到了一个小问题，可能是QQ的锅：当时用的账号突然不能更改白天/夜间模式了，提示“操作过于频繁，请稍后再试”，其他账号都可以更改，而且关闭LiteLoader以后仍然这样，甚至重装了一遍QQ也不行，囧~
如果您知道如何清除相关配置，感激不尽

**Comment by nfnfgo** [comment]
您好，关于您提到的操作过于频繁的问题，我暂时没有遇到过，也不知道如何解决。

不过好消息是，我这边可以成功复现您说的问题，并且目前看起来是个比较容易修复的问题，我会尝试修复，如果成功的话，会在近期提交PR

**Comment by nfnfgo** [comment]
问题目前确认的是，由于本插件渲染后的HTML元素中丢失了`text-normal`这个class，而Telegram对于文字的上色的CSS选择器似乎依赖于这个classes，经过简单的修改后，问题在我的测试环境下已经解决：

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/27c86e62-ecdf-44ee-854b-f06679fafc87)

我会于近期提交PR

**Comment by nfnfgo** [comment]
您好，PR已经通过了，请尝试更新到最新版本。

如果问题未解决，您可以重新开启本issue
