### ISSUE TITLE
Github Action Generated Release file contains `node_modules`

### ISSUE THREAD

**Issue by nfnfgo** [d0j1a1701/LiteLoaderQQNT-Markdown#53]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/c13e3c83-93c4-4563-ae7b-d133ce6dd411)

As image shows above. `node_modules` should NOT be included in release file.

**Comment by Ikaleio** [comment]
...似乎打包的时候把 node_modules 打包进去了，上传 Artifect 前把它删了就行。
