### ISSUE TITLE
Markdown 渲染器自动添加的 <p> 标签与其他插件的消息时间显示冲突

### ISSUE THREAD

**Issue by Ikaleio** [d0j1a1701/LiteLoaderQQNT-Markdown#56]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/48874489/48857409-e5ed-42d7-9017-558a7c1a0923)

如图，时间与消息间被强制添加一个换行，在单行消息情况下尤为明显。

暂定解决方案：特判，删除单行消息前后包裹的 `<p>`。

**Comment by Ikaleio** [comment]
已试图在最新版本中修复。

**Comment by nfnfgo** [comment]
我试了一下，刚刚的commit似乎会导致所有消息的时间显示都被放置在右边，不知道你那边是否能复现。

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/e3c66dd7-f851-4cb0-a8c7-35a14052a011)

**Comment by Ikaleio** [comment]
呃 他本来不应该在右边吗

**Comment by nfnfgo** [comment]
单行在右边确实是看起来舒服很多，但是我这边多行的消息时间也被放在了右边（）

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/0eb3504c-d540-44b2-a509-e0e5768a0cd4)

我个人感觉多行的情况下还是显示在最下面会好一点（大概？）不过也可能每个人习惯不一样

**Comment by Ikaleio** [comment]
哦 你说这个啊

不过我并没有什么很好的思路去改，这个 Commit 只是一个临时的 Workaround，因为单行换行一下实在太丑了。

**Comment by xiyuesaves** [comment]
或许我那边可以做个判断，在检测到启用了 Markdown 插件后强制将时间移动到气泡外部？

**Comment by Ikaleio** [comment]
@xiyuesaves 昨天的最后一个 Release 应当修复了这个问题

**Comment by xiyuesaves** [comment]
> @xiyuesaves 昨天的最后一个 Release 应当修复了这个问题

ok，我看 issue 没有关闭以为还没处理好，那就没我啥事了）

**Comment by Ikaleio** [comment]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/48874489/9c57cd56-68af-4912-b645-a2f7efdc727a)

还是不对劲，部分长消息的消息框会比别的消息长。

以下是关闭插件效果：
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/48874489/e41d870c-4aea-4e67-a730-d628795da3be)

**Comment by Ikaleio** [comment]
可以注意到同一条消息开启插件后首先自动折行没了其次本应该单换一行而不再右移的时间框再次右移了。

**Comment by nfnfgo** [comment]
目前的解决方案确实不够好（）所以当初说的是 "should not be considered as the final solution" 可是我没想到有什么好办法，或许我觉得也许应该尝试一下抛弃直接更改CSS，转而采用你之前说的那种特判方案？

如果采用特判方案，`renderer.jsx` 里面的`<div class="text-normal"></div>`元素类型要改成`span`，否则特判去除了`<p>`包裹似乎也没用。(之前在DevTools浅试了一下)

**Comment by d0j1a1701** [comment]
@nfnfgo 有没有 Telegram 上个 IM 沟通可能方便一点

**Comment by nfnfgo** [comment]
https://t.me/+_knOjtbIgZ8yYWE9

**Comment by nfnfgo** [comment]
> ![image](https://private-user-images.githubusercontent.com/48874489/346158798-9c57cd56-68af-4912-b645-a2f7efdc727a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzcyNzUsIm5iZiI6MTcyMDIzNjk3NSwicGF0aCI6Ii80ODg3NDQ4OS8zNDYxNTg3OTgtOWM1N2NkNTYtNjhhZi00OTEyLWI2NDUtYTJmN2VmZGM3MjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAzMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzQyZWEwNTU0NzE5NTc0N2ZiZDMzOGYwMjkyZDUwYTYzYjY5MWMyMGY2YmVhMjk4YWI1NjRmMTU1ZjBkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SNzVAVPgQ3zCq17_kTVL0f6cO5GCsyWFQ7aE-QjuR-s)
> 
> 还是不对劲，部分长消息的消息框会比别的消息长。
> 
> 以下是关闭插件效果： ![image](https://private-user-images.githubusercontent.com/48874489/346159994-e41d870c-4aea-4e67-a730-d628795da3be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzcyNzUsIm5iZiI6MTcyMDIzNjk3NSwicGF0aCI6Ii80ODg3NDQ4OS8zNDYxNTk5OTQtZTQxZDg3MGMtNGFlYS00ZTY3LWE3MzAtZDYyODc5NWRhM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAzMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZmQ3Yjc5YzMwY2FlYTM1Zjk4NWVhNWExMTdkNWE2ZGIxODc5NmIwOTBkYjU0M2U5MTQ3NWNjMDY0NmI4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vfso1kSHGhcZzE4LSmxKM9nsasCPn8pWD_O3Q9YdIxo)

关于这个问题，我又测试了一下，有以下发现。

首先，关于我那次 Workaround 的原理，本质上就是用JS手动确认某个消息的消息框的 `height` ，如果比一行略高（具体的高度Threshold我忘记设置了多少，可以查看代码），则认为是多行消息，`flex-direction` 属性则会被修改为 `column`。

该测试脚本只会在每次 `render` 函数被调用时触发，意味着如果当发送消息之后改变 `viewport` 大小（比如对QQNT界面进行Resize）是不会触发这个测试脚本的。而我这边只有对QQ的Window进行Resize之后才会出现你给出的例子的情况。

### 由小变大的Resize

这种情况下，在原来更小的屏幕上，消息多行显示，调整Size之后消息变为单行，但是`flex-direction=column`保持，所以会造成单行消息，时间仍换行。

### 由大变小的Resize

同理，这种情况下，原来的消息单行显示，时间在右边。调整Size后，消息被挤压到多行显示，但是`flex-direction=row`保持，则会出现你提供的图中的情况。

其余情况暂时未发现时间显示错误问题。
