### ISSUE TITLE
多行文本会被渲染到同一行

### ISSUE THREAD

**Issue by xh321** [d0j1a1701/LiteLoaderQQNT-Markdown#6]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/37585529/7271867f-e490-4a3b-88c1-752e9b622bf9)
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/37585529/e43b5b63-1cc6-49b6-b8fb-ffb1fc4cbed8)

**Comment by Ikaleio** [comment]
🤢

**Comment by Ikaleio** [comment]
Markdown 换行本来就是需要两个换行符的

这不是Bug 这是Feature

**Comment by xh321** [comment]
> Markdown 换行本来就是需要两个换行符的
> 
> 这不是Bug 这是Feature

我的意思是，群友发的消息都挤到一行去了。这些东西并不需要当作markdown去渲染的

**Comment by Ikaleio** [comment]
暂时还没加特判，后续会加开关，正在写 UI，llnt 的 UI 太难写了

**Comment by zhulinyv** [comment]
https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/pull/13
