### ISSUE TITLE
与轻量工具箱「已撤回」标签冲突

### ISSUE THREAD

**Issue by Ikaleio** [d0j1a1701/LiteLoaderQQNT-Markdown#60]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/48874489/e751f0da-9081-4b6b-b3b4-5e595602212e)

**Comment by nfnfgo** [comment]
Expected Behaviour应该是怎么样的（）

**Comment by Ikaleio** [comment]
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/48874489/4f73f6aa-12e7-4c6d-894b-80c26b8c6cd1)

**Comment by Eletary** [comment]
我自己测试好像渲染后的消息防撤回会直接失效，未渲染的不会

**Comment by nfnfgo** [comment]
![image](https://github.com/user-attachments/assets/7fa28e95-552e-461c-9750-408a864eb162)

开发分支中似乎该问题已经被修复（如果PR能过的话）。
