### ISSUE TITLE
在非程式碼區塊中無法正確渲染反斜線（跳脫字元）

### ISSUE THREAD

**Issue by EvanHsieh0415** [d0j1a1701/LiteLoaderQQNT-Markdown#62]
在非程式碼區塊中輸入 `\{ \} \[ \] \_ \\` 等都會被渲染成 `{ ] [ ] _ \`
![圖片](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/74277414/2121e70e-069a-4be6-b53c-ff9bf43d4c1e)

**Comment by nfnfgo** [comment]
在 Markdown 语法中，本身就包含了关于部分特殊字符转义的规则，具体内容可以参考 [Markdown Guide - Escaping Characters](https://www.markdownguide.org/basic-syntax/#characters-you-can-escape)。

因此，就我个人认为，这种行为应该被认为是 Markdown 渲染器的正常处理，不应该被认为是 Bug 。

![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/61616918/a5aba668-b7cb-4169-9a39-49e0a42f78e0)
