### ISSUE TITLE
[BUG] 回复和聊天消息显示顺序错误

### ISSUE THREAD

**Issue by jhqwqmc** [d0j1a1701/LiteLoaderQQNT-Markdown#69]
问题如图所示
![image](https://github.com/user-attachments/assets/d1b43a82-0539-454b-94a0-2076958b023c)

**Comment by jhqwqmc** [comment]
这个是我的配置
![image](https://github.com/user-attachments/assets/8c98531a-e66d-461e-b190-c53b2e83deaf)

**Comment by nfnfgo** [comment]
本问题已经在 dev branch 中修复，修复会随下次版本更新推送。
