### ISSUE TITLE
安装后无效果

### ISSUE THREAD

**Issue by KomoriDev** [d0j1a1701/LiteLoaderQQNT-Markdown#7]
我将插件安装至 `C:\Users\Administrator/Documents/BetterQQNT`，重启QQ没有效果，而且LiteLoader配置页面也没了（
安装前：
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/110453675/6effa187-9418-4c15-9fdd-9c00b240419d)
安装后：
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/110453675/db4d5b87-e739-410d-8546-812b36d76383)

**Comment by KomoriDev** [comment]
补充：我是通过 `git clone` 来安装的插件
![image](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown/assets/110453675/5ae5cf6c-7705-4d53-9267-3e24fede4762)

**Comment by bty552** [comment]
我也是这样LiteLoader配置页面也没有了

**Comment by KomoriDev** [comment]
> 我也是这样LiteLoader配置页面也没有了

有解决吗（

**Comment by GreyElaina** [comment]
https://github.com/GreyElaina/LiteLoaderQQNT-Markdown

试试我的分支, 我顺便修复了图片的样式不正确.

**Comment by KomoriDev** [comment]
> https://github.com/GreyElaina/LiteLoaderQQNT-Markdown
> 
> 试试我的分支, 我顺便修复了图片的样式不正确.

可以了！谢谢佬
