### ISSUE TITLE
Release 2.3.5的zip似乎传成了2.3.4的

### ISSUE THREAD

**Issue by QingFeng-awa** [d0j1a1701/LiteLoaderQQNT-Markdown#70]
2.3.5的commits把
```
return path.join(LiteLoader.plugins.markdown_it.path.plugin, 'log', `${logFileName}.log`);
```
修改成了
```
return path.join(LogPathHelper.getLogFolderPath(), `${logFileName}.log`);
```
Release里2.3.5的文件却仍然是
```
return path.join(LiteLoader.plugins.markdown_it.path.plugin, 'log', `${logFileName}.log`);
```
![image](https://github.com/user-attachments/assets/945c6586-082a-4c0b-827c-92f74d46d5fb)

> 要不是因为[list-viewer](https://github.com/ltxhhz/LL-plugin-list-viewer)一直提示需要更新我还不知道……
虽说这个影响不大,但还是希望作者改成正确的。

**Comment by nfnfgo** [comment]
您好，感谢您的反馈！

目前已经重传 `2.3.5` 的压缩包。

**Comment by Ikaleio** [comment]
看来要弄个 GitHub Action 自动上传 Release 了（
