### ISSUE TITLE
[bug?]关闭Linkify后仍然在链接末尾忽略\n换行符

### ISSUE THREAD

**Issue by Aliorpse** [d0j1a1701/LiteLoaderQQNT-Markdown#71]
如题, #65 
关闭markdown后没有这个问题

**Comment by nfnfgo** [comment]
测试了一下，确实可以复现该问题。

目前初步猜测是因为 QQNT 自身其实也会对链接进行 Linkify 导致的。且关闭 HTML渲染 功能后该问题也会消失，我想想有没有什么解决办法（）
