### ISSUE TITLE
复选框没有正确渲染

### ISSUE THREAD

**Issue by SsuJojo** [d0j1a1701/LiteLoaderQQNT-Markdown#72]
- [x] 像这样
- [x] 111

**Comment by nfnfgo** [comment]
感谢您的反馈。

目前，本插件使用 [MarkdownIt](https://github.com/markdown-it/markdown-it?tab=readme-ov-file) 对消息进行渲染，复选框并不在支持的范围之内，故目前并不支持。

不过在未来可能会通过 mdit 插件的方式引入该功能。
