### ISSUE TITLE
图片后的标题没有渲染

### ISSUE THREAD

**Issue by Yesbaiwan** [d0j1a1701/LiteLoaderQQNT-Markdown#73]
1. 如图所示：图片后的一个二级标题没有渲染，图片是以链接形式给出的：![]()
![image](https://github.com/user-attachments/assets/9fef10f8-3f1e-470b-b5e4-ae0661f2ad09)
疑似是图片和标题显示在了同一行（我把!删除后，这个二级标题和图片出现在了同一行：![]()## 总结）

2. 希望图片（链接）可以自定义大小
起因：链接中的图片太宽而不能完整显示

**Comment by nfnfgo** [comment]
该问题是由于内部的元素替换机制导致的，一个快速的 workaround 是多用一个换行符

```
[img]

## Title
```
