### ISSUE TITLE
插件将消息结构修改导致Telegram Theme主题错位

### ISSUE THREAD

**Issue by html5syt** [d0j1a1701/LiteLoaderQQNT-Markdown#74]
> 已确认是 markdown-it 插件将消息结构修改导致的现象，如图
> 
> 由于 markdown 渲染后的 HTML 中文字内容没有标签包裹，我这里大概做不了适配
> 
> PS：TG 主题普通文字气泡圆角样式也会受 markdown 插件影响
> 
> ![image](https://private-user-images.githubusercontent.com/36254268/356845234-586049da-a541-47de-b1cb-2c4e04aeabf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDU3NDcsIm5iZiI6MTcyMzM0NTQ0NywicGF0aCI6Ii8zNjI1NDI2OC8zNTY4NDUyMzQtNTg2MDQ5ZGEtYTU0MS00N2RlLWIxY2ItMmM0ZTA0YWVhYmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDAzMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNjUxMjQ0NDk2ZDA2MzVjOGI5MTQyY2I5ZDhhMWNiNWZiMTcwNGE1NGY2NzU5NzMzYTliNjIxZTM2YzE2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.28JpcOdBbxlElXl4Jhm8oyie_eQtfhC1fLNjGMHeHZw)

[https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/issues/46#issuecomment-2282345087](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/issues/46#issuecomment-2282345087)

以上是我与该主题作者的交流，最终发现markdown-it对消息中的文字内容没有使用标签而无法针对性适配。我在排查问题的过程中也发现了该现象但无法使用自定义CSS进行修改。

希望作者可以在修改消息结构时对文字部分也添加一个标签，感谢。

**Comment by nfnfgo** [comment]
感谢您的反馈。

该问题可以被成功复现，MarkdownIt插件在当前版本确实会对消息结构进行改动。

我目前正在尝试对本插件的渲染逻辑进行改动，使其能更加适配QQ消息的HTML结构。好消息是，在开发中，实测本问题已经被解决，如果没有意外，我们会在下一个版本更新中解决这个问题。
