### ISSUE TITLE
[FeatureRequest] 回复消息显示在上方

### ISSUE THREAD

**Issue by tanhHeng** [d0j1a1701/LiteLoaderQQNT-Markdown#76]
当前显示回复消息时，被回复的消息内容通常显示在原文本下方：

---
原文本原文本原文本
> XXX: 被回复的消息

---

是否可以添加一个设置项，让被回复的消息显示在上方

**Comment by nfnfgo** [comment]
这个问题之前似乎有人提过，如果没记错的话，我们好像已经在dev分支修复了，不过目前还没有release
