### ISSUE TITLE
新版本QQ（27187）明显卡顿

### ISSUE THREAD

**Issue by phillaria** [d0j1a1701/LiteLoaderQQNT-Markdown#77]
经测试，自QQ 9.9.15-27187版本以来，插件明显导致QQ卡顿，希望能对新版本QQ进行优化
测试过程：
安装Markdown_it插件，反复开启并关闭群助手，QQ会卡顿直到彻底无法操作；
删除Markdown_it插件，重复以上操作，QQ无明显卡顿感

**Comment by nfnfgo** [comment]
![image](https://github.com/user-attachments/assets/40bb3d60-9d95-4687-b880-039229e8e481)

我在如上图所示版本的Windows QQNT中，无法成功复现本问题。将QQ更新到当前最新版本后此问题是否仍然存在呢？

**Comment by phillaria** [comment]
> ![image](https://private-user-images.githubusercontent.com/61616918/378174610-40bb3d60-9d95-4687-b880-039229e8e481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MjAxMTQsIm5iZiI6MTczMTUxOTgxNCwicGF0aCI6Ii82MTYxNjkxOC8zNzgxNzQ2MTAtNDBiYjNkNjAtOWQ5NS00Njg3LWI4ODAtMDM5MjI5ZThlNDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDE3NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzdkY2E5ZjA2MDc1NmYyYjM3NDg3NDY1YzRhYzM1MDYxNTQ0Yzg1Nzk3OWQ0NGIwZDRjZGNlMTI5MDVmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6xm0ym3-DPrrAXl22_3aLhPCcJrjJrsxDwU2cffPbWw)
> 
> 我在如上图所示版本的Windows QQNT中，无法成功复现本问题。将QQ更新到当前最新版本后此问题是否仍然存在呢？

开发者大佬您好，更新后仍然如此。
安装markdown-it后：
![image](https://github.com/user-attachments/assets/8c16f712-19db-47d3-82d3-f1b556aaeede)
删除markdown-it后：
![image](https://github.com/user-attachments/assets/fc01181c-f4cb-4ed9-8c60-9f167bd4ab9b)
插件和qq版本：
![image](https://github.com/user-attachments/assets/a3411fec-dbdd-4339-8730-ae8ec983c4fe)
markdown-it插件版本：2.4.1

**Comment by phillaria** [comment]
再次测试，发现markdown-it插件并不是导致qq高占用cpu的根本原因，而只是作为催化剂（即加快了这个过程，删除markdown-it仍然会有高占用现象，只是占用程度不至于卡死，且比安装markdown-it要多运行十几分钟后才能看出），故产生了错误判断。
