### ISSUE TITLE
有个小bug

### ISSUE THREAD

**Issue by lehhair** [d0j1a1701/LiteLoaderQQNT-Markdown#8]
安装后点开图片会扭曲，要调整窗口大小才能恢复正常，关闭模块后一切正常

**Comment by zhulinyv** [comment]
同样的问题，mark 一下

**Comment by GreyElaina** [comment]
https://github.com/GreyElaina/LiteLoaderQQNT-Markdown

我的分支修复了这个问题.

**Comment by lehhair** [comment]
> https://github.com/GreyElaina/LiteLoaderQQNT-Markdown
> 
> 我的分支修复了这个问题.

感谢

**Comment by Ikaleio** [comment]
已解决 请更新
