### ISSUE TITLE
Latex里面 如$ a $，a两端加上空格就不渲染了

### ISSUE THREAD

**Issue by FeJS8888** [d0j1a1701/LiteLoaderQQNT-Markdown#82]

**Comment by nfnfgo** [comment]
理论上来说这两边确实是不能有空格的，我个人认为这个不属于bug。

作为例子，可以看下 GitHub 对于这种情况的渲染策略，两边有空格的时候也是不会渲染成 LaTeX 的，如下：

- `$a$`: $a$
- `$ a $`: $ a $
